### ISSUE TITLE
El archivo .vscode/settings.json genera conflicto

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#108]
Hace tiempo se realizó un commit que dejaba el archivo descrito en el título con la ruta del binario de python para su ejecución por parte de VSCode.

Hoy he clonado la rama developAuthentication y estoy recibiendo un aviso en Github Desktop de que mi VSCode ha sustituido dicha línea por la respectiva en Ubuntu.

Dejo un enlace al commit en cuestión, que lo hizo Martín con su antigua cuenta. La solución que propongo es añadir dicho archivo al .gitignore, para evitar conflictos entre sistemas operativos.

https://github.com/pabfrasan/decide/commit/78b1e8e9454a19ca99fcd24ef3dbbfdbbe0a627a

**Comment by Martinagr32** [comment]
Sí, creo que la solución que propones es la más indicada.

**Comment by PedroCoza** [comment]
Perfecto, procedo a ello entonces, ¡¡muchas gracias!!
