### ISSUE TITLE
I-006-B Test que pruebe que un usuario logeado no puede acceder al registro

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#129]
Actualmente, no existe un test en el sistema que pruebe que a un usuario ya logeado no se le permite el acceso al formulario de registro. Sería conveniente implementar dicho test de cara a aumentar el coverage de pruebas.

Los test deberán implementarse en el siguiente fichero: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/tests.py

**Comment by Andagualh** [comment]
Ya está creado, adjunto el commit con la solución desarrollada: https://github.com/pabfrasan/decide/commit/215b9aad81d61d0a12b50506fdddf2ae46febd05

Se verá reflejado en el siguiente pull request.
