### ISSUE TITLE
I-007-B No existe un botón de edición de perfil

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#133]
Actualmente solo se puede acceder al formulario de edición del perfil de usuario mediante URL, haría falta incorporar un botón que ponga esto más a la mano.

https://github.com/pabfrasan/decide/pull/132

**Comment by pabmordel** [comment]
Implementado el botón de editar perfil, tal como se puede observar en el siguiente pull request:
https://github.com/pabfrasan/decide/pull/172
