### ISSUE TITLE
I-008-B Cualquier persona puede editar un perfil

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#134]
Cualquier usuario puede acceder a la edición de perfil de otro usuario si introduce la URL adecuada, debería haber un proceso de autorización.

**Comment by pabmordel** [comment]
Se ha añadido un proceso de autorización para que solo el usuario en cuestión pueda ver y editar sus datos personales en el siguiente pull request:
https://github.com/pabfrasan/decide/pull/172
