### ISSUE TITLE
I-009-B Redirección tras edición de perfil

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#135]
La redirección tras la edición de un usuario no es válida, debería redirigir al perfil actualizado.

**Comment by pabmordel** [comment]
Se ha solucionado el problema de redireccionamiento, ahora una vez que el perfil es editado el usuario es redirigido a su página de perfil con los datos actualizados. Realizado en la siguiente pull request:
https://github.com/pabfrasan/decide/pull/172
