### ISSUE TITLE
I-011-B Test de modelo Profile

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#139]
Actualmente, no existe un test en el sistema que pruebe el modelo del módulo authentication. Sería conveniente implementar dicho test de cara a aumentar el coverage de pruebas.

Los test deberán implementarse en el siguiente fichero: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/tests.py

**Comment by Andagualh** [comment]
Ya han sido incluidos, adjunto el pull request asociado: https://github.com/pabfrasan/decide/pull/140
