### ISSUE TITLE
I-012-B Enlazar cuentas sociales con una cuenta ya creada

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#142]
Tras comprobar los commits realizados en developAuthentication me he percatado de que la funcionalidad para cambiar los datos de usuario no contiene botones para enlazar la cuenta en la que se está autenticado con las redes sociales, para poder iniciar sesión usandolas.

Para implementarlo bastaría con añadir los botones presentes en `login.html`, los siguientes:

```
          <a href="{% url 'social:begin' 'twitter' %}" class="btn btn-block btn-outline-info"> <i class="fab fa-twitter"></i>   Enlazar a Twitter</a>
            <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-block btn-outline-primary"> <i class="fab fa-facebook-f"></i>   Enlazar a facebook</a>
```

La librería django-social ya se encarga de asociar la cuenta autenticada en sesión con la cuenta de la red social que se haya elegido.

**Comment by pabmordel** [comment]
Incidencia solucionada, ya se ha implementado el botón en la página de perfil. Se puede observar en el siguiente commit:
https://github.com/pabfrasan/decide/commit/39f193f2e661e6fbadc06f20720dd55fc698b5ba
