### ISSUE TITLE
I-013-B La vista register no gestiona algunos errores importantes

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#159]
A la hora de registrar un usuario, existen algunos posibles errores que pueden saltar a la hora de efectuar un registro y los cuales ahora mismo no se controlan en la vista del registro. 

Estos errores se tratan en el modelo a la hora de crear un perfil y podemos observarlo en el siguiente código:
```
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, help_text='Mandatory, must be fulfilled')
    email_confirmed = models.BooleanField(default=False)
```

Estos errores son los siguientes:
- El sistema no aceptara una entrada de más de 30 caracteres en el campo 'first_name'
- El sistema no aceptara una entrada de más de 100 caracteres en el campo 'last_name'
- El sistema no aceptara una entrada de más de 254 caracteres en el campo 'email'

Esto se podría solucionar haciendo uso del atributo maxlength="integer" en los inputs que necesitan controlarse.
El archivo sobre el que se debe trabajar se trata de https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/templates/register.html

**Comment by Andagualh** [comment]
Ya está terminado, aquí enlazo el pull request asociado: https://github.com/pabfrasan/decide/pull/160
