### ISSUE TITLE
I-014-B Creación de Tests faltantes de Registro

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#161]
Actualmente los tests unitarios de registro carecen de pruebas para el límite de caracteres en 3 campos:

```
first_name
last_name
email
```

Dichos campos definen su valor máximo en el modelo y en el formulario de registro:
Enlace al modelo: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/models.py
```

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, help_text='Mandatory, must be fulfilled')
```

Enlace al forms: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/forms.py

```
    email = forms.EmailField(required=True, max_length=254)
    first_name = forms.CharField(required=False, max_length=30)
    last_name = forms.CharField(required=False, max_length=100)
```

Se debe comprobar que estos datos no pueden pasar del límite de caracteres.

**Comment by ivanhr3** [comment]
Se han implementado dichos tests en el sistema.
Se puede observar el código en el siguiente pull request: https://github.com/pabfrasan/decide/pull/167
