### ISSUE TITLE
I-015-B Posibilidad de editar el email de registro

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#163]
Actualmente, según el código subido en https://github.com/pabfrasan/decide/pull/132, el usuario tiene la posibilidad de editar el email con el que se registró y que fue validado. Esto no debería ser posible.

**Comment by pabmordel** [comment]
Se ha imposibilitado la edición del email del usuario. Implementado en la siguiente pull request:
https://github.com/pabfrasan/decide/pull/172
