### ISSUE TITLE
I-017-B Cambiar y esconder API Keys

### ISSUE THREAD

**Issue by pabmordel** [pabfrasan/decide#181]
Las API Keys presentes en settings.py deben estar fuera del control de versiones.
Para solucionar esto se deben añadir al fichero local_settings.py (Y lo deben hacer todos los miembros del grupo) y luego cambiar la referencia en el fichero settings.py.

Como ya se han subido las antiguas al repositorio anteriormente por  seguridad se deben crear nuevas aplicaciones en los respectivos servicios:
-Facebook
-Twitter

**Comment by Andagualh** [comment]
Solucionado en el siguiente pull request: https://github.com/pabfrasan/decide/pull/183
