### ISSUE TITLE
I-020-B No existen tests para logout

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#192]
Actualmente, no existe un test en el sistema que pruebe el logout de un cierto usuario. Sería conveniente implementar dicho test de cara a aumentar el coverage de pruebas.

Los test deberán implementarse en el siguiente fichero: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/tests.py

**Comment by Andagualh** [comment]
Solucionado en el siguiente pull request: https://github.com/pabfrasan/decide/pull/193
