### ISSUE TITLE
I-DOC-021-B Sección ''Resumen ejecutivo'' de la documentación

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#207]
Es necesario recabar la información necesaria para crear la sección ''Resumen ejecutivo'' en la documentación general del proyecto.
Esta es una de las tareas definidas en el desarrollo del proyecto.

**Comment by pabmordel** [comment]
El documento ha sido redactado y está publicado en formato wiki.
Cierro la incidencia.
