### ISSUE TITLE
I-DOC-022-B Sección "Gestión de incidencias" de la documentación

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#209]
Es necesario recabar la información necesaria para crear la sección ''Gestión de incidencias'' en la documentación general del proyecto. En dicha sección se tendrá que definir un plan de gestión de incidencias tanto internas, como externas, en el que se detalle el proceso a seguir cuando surja una incidencia, así como el formato que tendrá que seguir la misma.

Esta es una de las tareas definidas en el desarrollo del proyecto.

**Comment by pabmordel** [comment]
La documentación ha sido redactada y finalizada en formato wiki.
Cierro la incidencia.
