### ISSUE TITLE
I-DOC-025-B Sección "Gestíón del código fuente" de la documentación 

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#214]
Es necesario añadir esta sección al Documento del Proyecto, en la que se detalle el proceso y las normas seguidas a la hora de crear commits, la gestión de las herramientas usadas y la forma de gestionar los repositorios.

**Comment by ivanhr3** [comment]
Dicha sección ha sido realizada y debidamente indexada a la documentación general del proyecto.
