### ISSUE TITLE
I-DOC-026-B Sección "Gestión de liberaciones, despliegue y entregas" de la documentación 

### ISSUE THREAD

**Issue by PedroCoza** [pabfrasan/decide#215]
Es necesario añadir al Documento del Proyecto una sección de identifique los procesos de liberación, despliegue, entregas y nombrado de entregables por los que se rige el equipo.

**Comment by ivanhr3** [comment]
Dicha sección ha sido realizada y debidamente indexada a la documentación general del proyecto.
