### ISSUE TITLE
I-029-A Pasar la verificación de email a producción

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#220]
Actualmente la verificación de email se encuentra en preproducción, por lo que la generación del email de verificación se produce en un modo debug, devolviendo el email por consola. 

Dado que el módulo authentication se encuentra actualmente en proceso de ser liberado y no se van a hacer más pruebas a dicha funcionalidad, se debería pasar a producción la generación de dicho email, de forma que el email no se genere en consola sino que sea enviado a la dirección de email necesaria.

Para ello se deberán realizar los cambios pertinentes en el archivo settings.py.

**Comment by Andagualh** [comment]
Listo, aquí esta el pull request asociado: https://github.com/pabfrasan/decide/pull/221. No olvides incluir la configuración necesaria en tu local_settings.
