### ISSUE TITLE
Uso de static en base.html

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#23]
Realizando tests para el formulario de registro presente en developAuthentication me he encontrado con errores del siguiente tipo:

`ValueError: Missing staticfiles manifest entry for "/images/english.jpg"`
Realmente no sé a que se debe ese error, sólo sé que se origina en el fichero `base.html` tras haber realizado la internacionalización.

En caso de querer reproducir el error, basta con crear un test que realice una `request` y cuya respuesta sea un html, esto debe hacerse a una ruta que tenga como respuesta un html que extienda de `base.html` (Como es el caso de `/authentication/logingui/`) 

Aquí adjunto un commit donde se añaden esta clase de tests: https://github.com/pabfrasan/decide/commit/b11cfc21b70345f878d59d61555ca3f574a2f787

Para circunventar este problema, temporalmente he añadido la siguiente configuración a los tests:
`@override_settings(STATICFILES_STORAGE='django.contrib.staticfiles.storage.StaticFilesStorage') `
Básicamente sobre-escribe temporalmente la configuración presente en `settings.py` para los archivos estáticos.

Las soluciones propuestas a este problema por mi parte podrían ser:
1. Referenciar los archivos estáticos de otra forma en `base.html`.
2. Si no fuese posible, cambiar la configuración en `settings.py` para los archivos estáticos siempre y cuando no rompa ninguna otra función del sistema.
3. En caso de no poder realizar ninguna de las anteriores, tener en cuenta la anotación de sobre-escritura a la hora de realizar tests que usen llamadas `get` o `post` cuya respuesta contenga un html.

Si hubiese algo que estuviese ignorando, por favor remarcadlo en las respuestas a esta incidencia.

P.D. Como no consigo encontrar al desarrollador que hizo la internacionalización entre las personas que puedo asignar a la incidencia, no puedo asignar a nadie más.

**Comment by Martinagr32** [comment]
El bug se debía a que usaba el path static de Django para acceder al directorio de carpetas. Se ha modificado a la ruta relativa para su correcto funcionamiento, a nivel de pruebas e interfaz.

Commit para arreglarlo: https://github.com/pabfrasan/decide/commit/2ec9007776ebe756b223a689044115459eba1ef7
