### ISSUE TITLE
Creación de Espacio de trabajo/Pipeline para Picaro-Autenticación (ZenHub)

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#53]
Dado el procedimiento de incidencias establecido, me veo en la necesidad de abrir esta incidencia para solicitar la creación de un pipeline o espacio de trabajo de ZenHub para el grupo de Autenticación. Dado que las incidencias anteriores eran incluidas en el espacio de Visualización.

La necesidad de establecer un nuevo espacio de trabajo de justifica por:
1. La posibilidad para otros equipos de abrir incidencias que se asignen al tablero de proyecto del equipo de autenticación.
2. Para evitar que futuras incidencias relacionadas con los sistemas de autenticación se añadan automáticamente al tablero de Visualización.

Adicionalmente, añadir como sugerencia para la futura reunión de colaboración el establecimiento de un tablero general para todos los equipos con miras de solucionar cuestiones que no encajan dentro de los subsistemas del proyecto como puede ser la creación de un html de inicio en la ruta `/index` o `/`.

**Comment by pabfrasan** [comment]
Muy buenas. Ya he creado un nuevo workspace de zenhub para el grupo de autentificación. Gracias por la recomendación del tablero común, la implementaré en un rato.
Si tenéis algún problema con el repositorio, no dudéis en contactar conmigo.
