### ISSUE TITLE
El bot de telegram no dice nada

### ISSUE THREAD

**Issue by Martinagr32** [pabfrasan/decide#66]
Probando la implementación del bot de telegram en mi ordenador, no crea ninguna notificación.
Remito video que lo prueba al compañero que lo implementó para que le sea más fácil ubicar el problema.

commit 2195fa8d716ef23eabef21ca612c436b902a656d
El problema era que se habia cambiado la id del canal de telegram. Ya esta solucionado

**Comment by pabfrasan** [comment]
Después de estudiar porque no funcionaba el bot, he conseguido arreglarlo. El problema estaba en la id del grupo de telegram. Ya esta funcional en la rama developVisualizer
