### ISSUE TITLE
Travis sólo está corriendo los tests del subsistema Mixnet

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#73]
Consultando la configuración de Travis y atendiendo a las trazas de salida de algunos commits (Como la siguiente ejecución: https://github.com/pabfrasan/decide/runs/1658083730 ; donde sólo corre 6 tests mientras que mi clase de tests tiene 10), me he percatado que en el archivo `.travis.yml` se está declarando el comando:
 `- coverage run --branch --source=. ./manage.py test mixnet --keepdb`

La composición de este comando me lleva a pensar que los tests que se están ejecutando cada vez que subimos un commit son aquellos del subsistema `mixnet` (Que sólo tiene 6 tests) y no aquellos que realmente queremos probar.

Por ejemplo si yo hiciese tests para mis funcionalidades, Travis con esta configuración no los correría (Como está ocurriendo en la ejecución enlazada).

Esto plantea algunas dudas:
1. ¿Esta configuración la debemos cambiar individualmente en nuestras ramas y luego a la hora de solucionar los conflictos que surjan en los pull request a `master`mantener la configuración que figure en `master`?
2. ¿Cuando se debería en master cambiar la configuración para correr todos los tests?
3. ¿Deberíamos correr sólo los tests de los subsistemas donde sí se ha producido un incremento o los de todos los subsistemas? Esto creo que se podría realizar de las siguientes maneras:
-`- coverage run --branch --source=. ./manage.py test subsistema1 subsistema2 --keepdb`
-Usando un comando por cada subsistema que queremos probar.

Añadir al tercer punto, que correr todos los tests puede llevar una gran cantidad de tiempo.
 
Cualquier detalle o error que haya cometido, por favor notadlo en la respuesta a esta incidencia. Asigno a la persona que ha trabajado en la configuración de Travis anteriormente.

**Comment by pabfrasan** [comment]
Buenas tardes.
Que solo ejecutara Mixnet es un error. Se puso de esa manera en las practicas, para hacer que las pruebas fueran más ligeras. Se me olvido quitar que solo se ejecute ese modulo, pero ya lo he arreglado. 
Ahora solo ejecuta las pruebas de los módulos trabajados que son: voting, visualizer, authentication.

Muchas gracias por notificar la incidencia. Un saludo
