### ISSUE TITLE
I-003-B La vista register no importa correctamente el archivo functions.js

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#92]
Al acceder a la vista de register.html, nos proporciona un error de tipo 404 en la consola del servidor. 

![image](https://user-images.githubusercontent.com/25999279/104247803-baaa7f80-5468-11eb-8894-b75ad6897dcd.png)

Esto provoca que algunas funciones de dicha vista se encuentren inactivas, como pasa con la barra del nivel de seguridad de la contraseña.

El commit donde se encuentra el código referenciado es https://github.com/pabfrasan/decide/commit/607a9820f141fc54c5802841f29ca7c4dfa1c7fa

**Comment by Andagualh** [comment]
Los archivos Javascript no pueden almacenarse en el fichero de templates, ahí sólo se introducen los html pertinentes. Django por defecto no intentará cargar un archivo Javascript desde la ruta que le has dado en `register.html`:

` <script type="text/javascript" src="../templates/functions.js"></script>`

Los ficheros Javascript deben ir colocados en el fichero static del proyecto para la configuración actual de nuestro proyecto, concretamente en la siguiente ruta:

`"../../static/js/functions.js"`

Es importante que lo referencies de ese modo, dado que si usas `{% static : functions.js %}` con la configuración actual podrías hacer fallar los tests tal y como ocurrió en esta incidencia: https://github.com/pabfrasan/decide/issues/23

**Comment by ivanhr3** [comment]
El error ha sido resuelto y ya funciona correctamente.
La solución se puede observar en https://github.com/pabfrasan/decide/commit/ead566e3c6dc0f4d48bfd3aac4468c67d831018c
