### ISSUE TITLE
I-004-B El test ''register_form_bad_pass" no prueba la no creacion del usuario

### ISSUE THREAD

**Issue by ivanhr3** [pabfrasan/decide#98]
En el test ''register_form_bad_pass'' no se comprueba que el usuario no sea introducido en la base de datos al tratarse de un formulario erroneo. Se comprueba la redirreción correctamente pero tras esto no se hacen las comprobaciones necesarias para verificar la no creación del usuario.

El código referenciado se trata del siguiente:
```
@override_settings(STATICFILES_STORAGE='django.contrib.staticfiles.storage.StaticFilesStorage')
    def test_register_form_bad_pass(self):
        response = self.client.post("/authentication/registergui/", data={
            'username' : self.username,
            'email' : self.email,
            'first_name': self.first_name,
            'last_name' : self.last_name,
            'password1' : '123',
            'password2' : '123'
        })
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, template_name = 'register.html')
```

El commit en el que se encuentra es https://github.com/pabfrasan/decide/commit/b11cfc21b70345f878d59d61555ca3f574a2f787

**Comment by Andagualh** [comment]
Ya está añadida la comprobación, en la incidencia aparecen los respectivos commit y pull request.

Adjunto el enlace del pull request: https://github.com/pabfrasan/decide/pull/101
