### ISSUE TITLE
I-005-B Creación de Test de Registro para Campos no Probados

### ISSUE THREAD

**Issue by Andagualh** [pabfrasan/decide#99]
Los test actuales para la funcionalidad de registro no tienen un coverage completo. 

Las únicas funciones que se están probando son:
-Comprobar si el campo de nombre de usuario esta relleno
-Comprobar si el campo de contraseña aplica correctamente los requisitos de complejidad
-Comprobar si se puede registrar un usuario con un formulario que cumpla los requisitos

Estos test se encuentran actualmente en el siguiente fichero: https://github.com/pabfrasan/decide/blob/developAuthentication/decide/authentication/tests.py

En este caso, los casos restantes a probar serían:
-Comprobar que el email es requerido
-Comprobar que no se acepta un email que no cumpla los requisitos de formato
-Comprobar que los campos de contraseña no pueden dejarse vacíos

Los tests restantes deberían comprobar que las respuestas http son las apropiadas y también que no se puede crear un usuario con estos errores.

**Comment by ivanhr3** [comment]
Los tests mencionados han sido implementados y se encuentran en el siguiente pull request https://github.com/pabfrasan/decide/pull/103
